export JISKEFET_HOST="123.456.789.0"
export JISKEFET_API_TOKEN="sdfsakafuih32784h342..."

export JISKEFET_MIGRATE_JISKEFETDB_DBNAME="jiskefetdb"
export JISKEFET_MIGRATE_JISKEFETDB_HOSTPORT="192.168.122.235:3306"
export JISKEFET_MIGRATE_JISKEFETDB_USERNAME="user"
export JISKEFET_MIGRATE_JISKEFETDB_PASSWORD="pass"

export JISKEFET_MIGRATE_LOGBOOKDB_DBNAME="LOGBOOK_ITSRUN3"
export JISKEFET_MIGRATE_LOGBOOKDB_HOSTPORT="127.0.0.1:3306"
export JISKEFET_MIGRATE_LOGBOOKDB_USERNAME="user"
export JISKEFET_MIGRATE_LOGBOOKDB_PASSWORD="pass"
export JISKEFET_MIGRATE_LOGBOOKDB_FILESDIR="/home/user/logbook/fileAttachments"
